#!/bin/bash

# testing single proxy:
alias p="source proxy proxy1.example.com 81"

# testing among 3 proxies:
#alias p="source proxy proxy1.example.com 81 || source proxy 10.1.1.1 8080 || source proxy proxy3.example.com 81"
