#!/bin/bash

# example with single proxy:
alias p="source proxy proxy1.example.com 81"

# example with three proxies:
#alias p="source proxy proxy1.example.com 81 || source proxy 10.1.1.1 8080 || source proxy proxy3.example.com 81"
